### PR TITLE
Add TypeScript module type definition

### PR DESCRIPTION
**Pull request by octatone**
Hi there, I recently needed a lock mechanism for coordinating modification of an async queue.

My project is in TypeScript.  This PR adds a type declaration for TypeScript > 2.x

### CODE REVIEW

**Comment by dominictarr** [comment]
I have hardly used this module since I wrote it, but I could transfer it to you and you could add type support

**Comment by octatone** [comment]
That works for me. Thanks.

**Comment by dominictarr** [comment]
@octatone you are now npm owner, I couldn't tranfer the repo to you because you already have a fork, so I made you collaborator instead, so you can push to this repo, or move it to under your name, up to you!

**Comment by octatone** [comment]
Thanks!

**Pull request merged**
